branches:
  only:
    - 'master'

language: ruby

rvm:
  - 2.0.0

env:
  - DB=mongodb

services: 
  - mongodb

before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
